services:
  app:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - db
    volumes:
      - ../:/app

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: lei_explorer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./postgres:/docker-entrypoint-initdb.d

volumes:
  db_data:
